### PR TITLE
feat: Add tcp_keepalive for native connections

### PR DESCRIPTION
**Pull request by rjoelnorgren**
## Summary

This PR closes https://github.com/ClickHouse/dbt-clickhouse/issues/233.

## Checklist
Delete items not relevant to your PR:
- [ ] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

**Comment by rjoelnorgren** [comment]
@genzgd, the tests for Python 3.9 should pass now.

**Comment by genzgd** [comment]
Thanks for the contribution!  We should be able to incorporate this into a release next week.  cc @BentsiLeviav

**Comment by barberscott** [comment]
What is the proper form to send in the tuple?

```
➜  analytics git:(main) ✗ dbt build --full-refresh --target local
04:12:34  Running with dbt=1.8.3
04:12:34  Encountered an error:
Runtime Error
  at path ['tcp_keepalive']: (30, 30, 10) is not valid under any of the given schemas
  
```
 Fails for me with:
 
```
       tcp_keepalive: 
        - 30
        - 30
        - 10
```

**Comment by rjoelnorgren** [comment]
@barberscott, I believe that should work. Can you share a complete profile.yaml and your dbt version?

**Comment by barberscott** [comment]
```
langsmith_analytics:
  target: local
  outputs:
    prod_local:
      type: clickhouse
      schema: analytics_local
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD_PROD') }}"
      host: "{{ env_var('CLICKHOUSE_HOST_PROD') }}"
      retries: 2
      verify: True
      secure: True
      driver: native
      connect_timeout: 10
      send_receive_timeout: 1800
      sync_request_timeout: 5
      check_exchange: False
      use_lw_deletes: False  
      tcp_keepalive: True
      custom_settings: 
        select_sequential_consistency: 1
        wait_for_async_insert: 1 
        max_threads: 24
        max_insert_threads: 24
        join_algorithm: 'auto'
    prod:
      type: clickhouse
      schema: analytics
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      retries: 2
      verify: True
      secure: True
      driver: native
      connect_timeout: 10
      send_receive_timeout: 1800
      sync_request_timeout: 5
      check_exchange: False
      use_lw_deletes: False
      tcp_keepalive: True
      custom_settings: 
        select_sequential_consistency: 1
        wait_for_async_insert: 1 
        max_threads: 24
        max_insert_threads: 24
        join_algorithm: 'auto'
    local:
      type: clickhouse
      schema: analytics_local
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      retries: 2
      verify: True
      secure: True
      driver: native
      connect_timeout: 30
      send_receive_timeout: 1800
      sync_request_timeout: 5
      check_exchange: False
      use_lw_deletes: False
      tcp_keepalive: True
      custom_settings: 
        select_sequential_consistency: 1
        wait_for_async_insert: 1 
        join_algorithm: 'auto'
    dev:
      type: clickhouse
      schema: analytics_dev
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      retries: 2
      verify: True
      secure: True
      driver: native
      connect_timeout: 30
      send_receive_timeout: 1800
      sync_request_timeout: 5
      check_exchange: False
      use_lw_deletes: False
      tcp_keepalive: [30,10,10]
      custom_settings: 
        select_sequential_consistency: 1
        wait_for_async_insert: 1 
        join_algorithm: 'auto'
    euprod:
      type: clickhouse
      schema: analytics
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      host: "{{ env_var('CLICKHOUSE_HOST') }}"
      retries: 2
      verify: True
      secure: True
      driver: native
      connect_timeout: 10
      send_receive_timeout: 1800
      sync_request_timeout: 5
      check_exchange: False
      use_lw_deletes: False
      tcp_keepalive: True
      custom_settings: 
        select_sequential_consistency: 1
        wait_for_async_insert: 1 
        max_threads: 10
        max_insert_threads: 10
        join_algorithm: 'auto'
```

dbt 1.8.4, dbt-clickhouse 1.8.1

**Comment by barberscott** [comment]
Tried also with the list form:

```
      tcp_keepalive: 
        - 30
        - 10
        - 10
```

and the form:
```
      tcp_keepalive: [30,10,10]
```

Same error either way.

**Comment by rjoelnorgren** [comment]
@barberscott thanks for sharing. I suspect the issue is with another dependency. What version of pydantic and pydantic-core are you using?

**Comment by barberscott** [comment]
```
➜  analytics git:(main) ✗ pip list | grep -i pydantic                                          
pydantic                                 2.8.2
pydantic_core                            2.20.1
```

**Comment by rjoelnorgren** [comment]
I can try to reproduce later this weekend when I have my machine available. It's a bit of a shot in the dark, but if you want to try pinning to this and seeing if it works, this is what I currently have in production.


pydantic==2.7.4
pydantic_core==2.18.4

**Comment by barberscott** [comment]
Hmm...may be macOS specific.  Clean install on ubuntu doesn't have the problem, so something else is going on here.  Thanks -- I'll open a separate issue if I track it down/

**Pull request merged**
