### PR TITLE
cluster names containing dash characters (#198)

### PR DESCRIPTION
**Pull request by the4thamigo-uk**
## Checklist
Delete items not relevant to your PR:
- [ ] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

**Review by zli06160 — APPROVED** [review]
I tested the modifications with the PR https://github.com/ClickHouse/dbt-clickhouse/pull/186, it worked well with `DBT_CH_TEST_CLUSTER=test-shard`(instead of `tedt_shard`).

Integration testing passed without failure.

There might be a conflict to resolve once the PR #186 merged.

**Comment by genzgd** [comment]
Also thanks for the contribution @the4thamigo-uk and the testing @zli06160.  It would make our legal folks happy if @the4thamigo-uk signed the CLA :)

**Comment by zli06160** [comment]
@genzgd In my opinion, backticks are more user-friendly or eye-friendly.

P.S. Integration testing with backticks passed too.

**Comment by the4thamigo-uk** [comment]
> Also thanks for the contribution @the4thamigo-uk and the testing @zli06160. It would make our legal folks happy if @the4thamigo-uk signed the CLA :)

Hmm... Ive signed this at least twice and it hasnt reflected in the status in the PR

**Comment by the4thamigo-uk** [comment]
> Do backticks works and are they safer?

I used double quotes as that's what I see in the other sql commands visible in the dbt logs. Possible if you change to back ticks then this could be a wider change to make for consistency.

**Comment by zli06160** [comment]
Agree with @the4thamigo-uk , we can make it simple and just keep `""`.

(Maybe @the4thamigo-uk the email address is not verified by github?)

**Pull request merged**
