### PR TITLE
feat: add TTL support

### PR DESCRIPTION
**Pull request by Ian2012**
## Checklist
Delete items not relevant to your PR:
- [x] Unit and integration tests covering the common scenarios were added
- [ ] A human-readable description of the changes was provided to include in CHANGELOG
- [ ] For significant changes, documentation in https://github.com/ClickHouse/clickhouse-docs was updated with further explanations or tutorials

### CODE REVIEW

**Comment by Ian2012** [comment]
@mshustov Can you take a look at this PR?
I'm waiting for suggestions to add tests

**Comment by BentsiLeviav** [comment]
Hi @Ian2012 ,

I would suggest to add a test with the following process:

1. create a table with X (3-5) seconds TTL
2. Insert data into it
3. Query the data to make sure it is there.
4. Make sure 3 seconds have passed since the insertion.
5. Call `OPTIMIZE TABLE example1 FINAL` to [force merge](https://clickhouse.com/docs/en/guides/developer/ttl#triggering-ttl-events) (will remove expired rows)
6. Query the table again to make sure it is empty.

With a bad network situation, this test could become a burden, therefore, I would implement a retry mechanism for steps 2 and 3 and would provide a way to skip the entire test if necessary (using a flag provided by environment variables). 

@genzgd WDYT?

**Comment by Ian2012** [comment]
@BentsiLeviav does the current test match your expectations?

`Note`: I was unable to run tests locally

**Comment by BentsiLeviav** [comment]
> @BentsiLeviav does the current test match your expectations?
> 
> **Note**: I was unable to run tests locally

Why? did you try to setup a docker environment?
I ran the test locally and it doesn't pass

**Comment by Ian2012** [comment]
@BentsiLeviav Ready for review

**Comment by BentsiLeviav** [comment]
I ran our workflows, and the only one that didn't pass is Lint, could you run it locally and fix the styling? (you can run `make lint` in the project directory before committing to know what to clean up)

**Comment by Ian2012** [comment]
@BentsiLeviav thanks for your review. I've reformated the files

**Pull request merged**
